config/routes.rb
Rails.application.routes.draw do
  resources :reading_lists
  resources :genres

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/edit_password', to: 'users/registrations#edit_password', as: :edit_password
    put 'users/update_password', to: 'users/registrations#update_password', as: :password_update
  end

  root to: "books#index"

  resources :users, only: [:index, :show, :edit, :update]

  resources :genres

  resources :authors do
    get 'books', to: 'authors#books', as: 'author_books'
  end

  resources :books do
    post 'add_to_reading_list', on: :member
  end
  
  resources :book_author_relation

  resources :reading_lists do
    post 'add_book', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :book_author_relations
    has_many :books, through: :book_author_relations

    acts_as_favoritable

    validates :author_name, presence: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_author, only: %i[ show edit update destroy ]

  def books
    @author = Author.find(params[:author_id])
    @books = @author.books 
  end

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_path, status: :see_other, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:author_name, :author_bio)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Author name:</strong>
    <%= author.author_name %>
  </p>

  <p>
    <strong>Author bio:</strong>
    <%= author.author_bio %>
  </p>

  <p>
    <strong>Author books:</strong>
    <ul>
      <% if author.books.any? %>
        <% author.books.each do |book| %>
          <li><%= link_to book.book_name, book_path(book.id) %></li>
        <% end %>
      <% else %>
        <li>No books found for this author.</li>
      <% end %>
    </ul>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :author_name, style: "display: block" %>
    <%= form.text_field :author_name %>
  </div>

  <div>
    <%= form.label :author_bio, style: "display: block" %>
    <%= form.text_area :author_bio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/books.html.erb
<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.book_name, book_path(book) %></li>
  <% end %>
</ul>

<%= link_to 'Back to Authors', authors_path %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th><%= "Authors" %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= "Author Name" %></td>
        <td><%= "Author's Books" %></td>
        <td><%= "Show Author" %></td>
        <td><%= "Edit Author" %></td>
      </tr>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.author_name %></td>
        <td><%= author.books.count %></td>
        <td>
          <%= link_to 'Show', author, class: "btn btn-secondary" %>
        </td>
        <td>
          <%= link_to 'Edit', edit_author_path(author), class: "btn btn-secondary" %>
        </td>
      </tr>
      
    <% end %>
      <tr>
        <td>
          <%= link_to "New Author", new_author_path, class: "btn btn-secondary" %>
        </td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
      </tr>  
  </tbody>
</table>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>